Repository VRGuild/VRGuild, pull requests merged in 2024-11, with the labels that each got.

#299 refectoring team api
  VRGuild/Source/VRGuild/Private/Global/API/CACTeamAPI.cpp
  VRGuild/Source/VRGuild/Private/Global/UI/API/CWGTeamAPI.cpp
  VRGuild/Source/VRGuild/Public/Global/API/BPL/CBPLTeam.h
  VRGuild/Source/VRGuild/Public/Global/API/CACTeamAPI.h
  VRGuild/Source/VRGuild/Public/Global/UI/API/CWGTeamAPI.h
Labels: ♻️ 리펙토링, 🌎 환경설정

#301 guild api
  VRGuild/Source/VRGuild/Private/Global/API/BPL/CBPLGuild.cpp
  VRGuild/Source/VRGuild/Private/Global/API/CACGuildAPI.cpp
  VRGuild/Source/VRGuild/Public/Global/API/BPL/CBPLGuild.h
  VRGuild/Source/VRGuild/Public/Global/API/CACGuildAPI.h
Labels: ♻️ 리펙토링, 🌎 환경설정

#312 comment api
  VRGuild/Source/VRGuild/Private/Global/API/BPL/CBPLComment.cpp
  VRGuild/Source/VRGuild/Private/Global/API/CACCommentAPI.cpp
  VRGuild/Source/VRGuild/Public/Global/API/BPL/CBPLComment.h
  VRGuild/Source/VRGuild/Public/Global/API/CACCommentAPI.h
Labels: ♻️ 리펙토링, 🌎 환경설정

#314 ether api created
  VRGuild/Source/VRGuild/Private/Global/API/BPL/CBPLEther.cpp
  VRGuild/Source/VRGuild/Private/Global/API/CACEtherAPI.cpp
  VRGuild/Source/VRGuild/Public/Global/API/BPL/CBPLEther.h
  VRGuild/Source/VRGuild/Public/Global/API/CACEtherAPI.h
Labels: ♻️ 리펙토링, 🌎 환경설정

#319 ⚡️ Feat : Overlay material (2)
  VRGuild/Content/Character/UI/Soundhover/M_Sound.uasset
  VRGuild/Content/Character/UI/Soundhover/M_Sound_Inst.uasset
  VRGuild/Content/Character/UI/Soundhover/shinningIndex.uasset
  VRGuild/Content/Hall/Blueprints/BP_CharacterHallPlayer.uasset
  VRGuild/Content/Hall/Blueprints/MyCAReceptionist.uasset
  VRGuild/Content/NPC/Material/M_Outline.uasset
  VRGuild/Source/VRGuild/Private/Global/CAInteractable.cpp
  VRGuild/Source/VRGuild/Private/Hall/Actors/CAReceptionist.cpp
  VRGuild/Source/VRGuild/Public/Global/CAInteractable.h
Labels: ♻️ 리펙토링

#328 ⚡️ Feat : Save Character Image
  VRGuild/Content/Character/Custom/Blueprints/BP_BasePlayerController_Custom.uasset
  VRGuild/Content/Character/Custom/RenderTarget/RT_Character_Custom_Inst.uasset
  VRGuild/Content/Character/Custom/UI/WBP_CharacterCustom.uasset
  VRGuild/Content/Global/API/AC_CharacterAPI.uasset
  VRGuild/Source/VRGuild/Public/Global/API/BPL/CBPLBase.h
Labels: ⚡️ 기능

#329 282 dv platform register review board
  VRGuild/Content/Hall/Blueprints/A_Displayer.uasset
  VRGuild/Content/Hall/Blueprints/BP_CharacterHallPlayer.uasset
  VRGuild/Content/Hall/Board/Notice/A_NoticeBoard.uasset
  VRGuild/Content/Hall/Board/Notice/UI/WBP_RefreshButton.uasset
  VRGuild/Content/TPS/ThirdPerson/Blueprints/BP_ThirdPersonCharacter.uasset
  VRGuild/Content/main/2_Hall/L_Hall2.umap
  VRGuild/Source/VRGuild/Private/Global/Components/CACInteraction.cpp
  VRGuild/Source/VRGuild/Private/Global/Widgets/CWBaseWorld.cpp
  VRGuild/Source/VRGuild/Private/Global/Widgets/TestWidgetComp.cpp
  VRGuild/Source/VRGuild/Private/Hall/Board/CANoticeBoard.cpp
  VRGuild/Source/VRGuild/Public/Global/Components/CACInteraction.h
  VRGuild/Source/VRGuild/Public/Global/Widgets/CWBaseWorld.h
  VRGuild/Source/VRGuild/Public/Global/Widgets/TestWidgetComp.h
  VRGuild/Source/VRGuild/Public/Hall/Board/CANoticeBoard.h
  VRGuild/Source/VRGuild/TP_ThirdPerson/TP_ThirdPersonCharacter.cpp
  VRGuild/Source/VRGuild/TP_ThirdPerson/TP_ThirdPersonCharacter.h
Labels: ♻️ 리펙토링, ⚡️ 기능

#365 상인 NPC Idle 추가
  VRGuild/Content/Character/NPC/Mesh/NPC_Seller_Animation_Idle_Anim.uasset
Labels: 🎨 스타일

#367 NPC 접수원 모델링,애니메이션 Idle 추가
  VRGuild/Content/Character/NPC/Material/Cloth_M1.uasset
  VRGuild/Content/Character/NPC/Material/NPC_Info_Body_MT.uasset
  VRGuild/Content/Character/NPC/Material/NPC_Info_Face_MT.uasset
  VRGuild/Content/Character/NPC/Material/NPC_Info_Hair_MT.uasset
  VRGuild/Content/Character/NPC/Mesh/NPC_Info_Animation_Idle_Anim.uasset
  VRGuild/Content/Character/NPC/Mesh/NPC_Info_v002.uasset
  VRGuild/Content/Character/NPC/Mesh/NPC_Info_v002_PhysicsAsset.uasset
  VRGuild/Content/Character/NPC/Mesh/NPC_Info_v002_Skeleton.uasset
  VRGuild/Content/Character/NPC/Texture/Info/SubStance_v001_Cloth_M1_BaseColor.uasset
  VRGuild/Content/Character/NPC/Texture/Info/SubStance_v001_Cloth_M1_Normal.uasset
  VRGuild/Content/Character/NPC/Texture/Info/SubStance_v001_Cloth_M1_OcclusionRoughnessMetallic.uasset
  VRGuild/Content/Character/NPC/Texture/Info/SubStance_v001_NPC_Info_Body_MT_BaseColor.uasset
  VRGuild/Content/Character/NPC/Texture/Info/SubStance_v001_NPC_Info_Body_MT_Normal.uasset
  VRGuild/Content/Character/NPC/Texture/Info/SubStance_v001_NPC_Info_Body_MT_OcclusionRoughnessMetallic.uasset
  VRGuild/Content/Character/NPC/Texture/Info/SubStance_v001_NPC_Info_Face_MT_BaseColor.uasset
  VRGuild/Content/Character/NPC/Texture/Info/SubStance_v001_NPC_Info_Face_MT_Normal.uasset
  VRGuild/Content/Character/NPC/Texture/Info/SubStance_v001_NPC_Info_Face_MT_OcclusionRoughnessMetallic.uasset
  VRGuild/Content/Character/NPC/Texture/Info/SubStance_v001_NPC_Info_Hair_MT_BaseColor.uasset
  VRGuild/Content/Character/NPC/Texture/Info/SubStance_v001_NPC_Info_Hair_MT_Normal.uasset
  VRGuild/Content/Character/NPC/Texture/Info/SubStance_v001_NPC_Info_Hair_MT_OcclusionRoughnessMetallic.uasset
  VRGuild/Content/Hall/maps/HallMap.umap
Labels: 🎨 스타일

#368 fix npc change and npc ui
  VRGuild/Content/Hall/Blueprints/BP_BarManager.uasset
  VRGuild/Content/Hall/Blueprints/MyCAReceptionist.uasset
  VRGuild/Content/NPC/UI/WBP_NPC_Templates.uasset
  VRGuild/Content/NPC/UI/WBP_npc_noneSettlement.uasset
  VRGuild/Content/main/2_Hall/L_Hall2.umap
Labels: 🎨 스타일

#387 Feat : Add NPC animation
  VRGuild/Content/Character/NPC/Animation/AM_NPC_Clapping.uasset
  VRGuild/Content/Character/NPC/Animation/AM_NPC_Thankful.uasset
  VRGuild/Content/Character/NPC/Animation/AN_NPC_Clapping_UE.uasset
  VRGuild/Content/Character/NPC/Animation/AN_NPC_HappyHandGesture_UE.uasset
  VRGuild/Content/Character/NPC/Animation/AN_NPC_Thankful_UE.uasset
  VRGuild/Content/Character/NPC/Animation/Mixamo/Clapping_UE.uasset
  VRGuild/Content/Character/NPC/Animation/Mixamo/HappyHandGesture_UE.uasset
  VRGuild/Content/Character/NPC/Animation/Mixamo/Thankful_UE.uasset
  VRGuild/Content/Character/Player/Animation/AM_HandRaising.uasset
  VRGuild/Content/Character/Player/Animation/AN_HandRaising_UE.uasset
  VRGuild/Content/Character/Player/Animation/mixamo/HandRaising_UE.uasset
  VRGuild/Content/Character/Player/Animation/montage/AC_AnimMontage.uasset
  VRGuild/Content/Hall/Blueprints/BP_BarManager.uasset
  VRGuild/Content/Hall/Blueprints/MyCAReceptionist.uasset
  VRGuild/Content/NPC/UI/WBP_NPC_Templates.uasset
  VRGuild/Content/NPC/UI/WBP_npc_popup_freelancer1.uasset
  VRGuild/Source/VRGuild/Public/Global/Components/CACCharacterAnimMontage.h
Labels: ⚡️ 기능

#391 Player info display HUD (hover)
  VRGuild/Content/Character/Custom/Blueprints/AC_MsgBoard.uasset
  VRGuild/Content/Character/UI/WBP_Character_Nickname.uasset
  VRGuild/Content/Global/API/AC_CharacterAPI.uasset
  VRGuild/Content/Hall/Blueprints/BP_CharacterHallPlayer.uasset
  VRGuild/Content/TPS/ThirdPerson/Blueprints/BP_ThirdPersonCharacter.uasset
  VRGuild/Source/VRGuild/TP_ThirdPerson/TP_ThirdPersonCharacter.cpp
  VRGuild/Source/VRGuild/TP_ThirdPerson/TP_ThirdPersonCharacter.h
Labels: ⚡️ 기능

#393 Fix player HUD info rotation towards player camera.
  VRGuild/Content/Character/Custom/Blueprints/AC_MsgBoard.uasset
  VRGuild/Content/Hall/Blueprints/BP_CharacterHallPlayer.uasset
  VRGuild/Content/TPS/ThirdPerson/Blueprints/BP_ThirdPersonCharacter.uasset
  VRGuild/VRGuild.uproject
Labels: 🐝 버그

#396 Spawning and posting Review Posters.
  VRGuild/Content/Hall/Board/Notice/A_NoticeBoard.uasset
  VRGuild/Content/Hall/Board/Notice/A_ReviewNotice.uasset
  VRGuild/Source/VRGuild/Private/Hall/Board/CANoticeBoard.cpp
  VRGuild/Source/VRGuild/Private/Hall/Board/CAReviewNotice.cpp
  VRGuild/Source/VRGuild/Public/Hall/Board/CANoticeBoard.h
  VRGuild/Source/VRGuild/Public/Hall/Board/CAReviewNotice.h
  VRGuild/VRGuild.uproject
Labels: 💻 작업

#399 Feat : restyle Hall Level
  VRGuild/Content/Global/Fonts/NotoSans.uasset
  VRGuild/Content/Global/Fonts/NotoSansKR-SemiBold.uasset
  VRGuild/Content/NPC/UI/Assets/TX_npc_dialog_back2.uasset
  VRGuild/Content/NPC/UI/WBP_NPCButton.uasset
  VRGuild/Content/NPC/UI/WBP_NPC_Templates.uasset
  VRGuild/Content/NPC/UI/WBP_npc_noneSettlement.uasset
  VRGuild/Content/main/2_Hall/L_Hall2.umap
Labels: 🎨 스타일

#402 Feat : Grab Furniture
  VRGuild/Content/TileSystem/Blueprints/AC_TileFurniture.uasset
  VRGuild/Content/TileSystem/Mesh/test/Test_Board.uasset
  VRGuild/Content/TileSystem/Mesh/test/Test_bookShelf.uasset
  VRGuild/Content/TileSystem/Mesh/test/Test_chair.uasset
  VRGuild/Content/TileSystem/Mesh/test/Test_floor.uasset
  VRGuild/Content/TileSystem/Mesh/test/Test_table.uasset
  VRGuild/Content/TileSystem/UI/Assets/TX_furniture_board.uasset
  VRGuild/Content/TileSystem/UI/Assets/TX_furniture_bookshelf.uasset
  VRGuild/Content/TileSystem/UI/Assets/TX_furniture_chair.uasset
  VRGuild/Content/TileSystem/UI/Assets/TX_furniture_floor.uasset
  VRGuild/Content/TileSystem/UI/Assets/TX_furniture_table.uasset
  VRGuild/Content/TileSystem/UI/WBP_TileFurniture.uasset
Labels: ⚡️ 기능

#404 포탈 이펙트
  VRGuild/Content/Effect/Portal/Black.uasset
  VRGuild/Content/Effect/Portal/M_Radial_Gradient.uasset
  VRGuild/Content/Effect/Portal/NewParticleSystem.uasset
  VRGuild/Content/Effect/Portal/NewParticleSystem1.uasset
  VRGuild/Content/Effect/Portal/Portal_Effect_MT.uasset
  VRGuild/Content/Effect/Portal/Portal_Effect_MT_2.uasset
  VRGuild/Content/Effect/Portal/Portal_Effect_MT_2_Inst_2.uasset
  VRGuild/Content/Effect/Portal/Portal_Effect_MT_Inst.uasset
  VRGuild/Content/Effect/Portal/Shape_Plane.uasset
  VRGuild/Content/Effect/Portal/T_Burst_M.uasset
  VRGuild/Content/Effect/Portal/T_Twirl_Hole.uasset
Labels: 🎨 스타일

#411 Assign data from API to Review poster
  VRGuild/Content/Global/API/AC_CharacterAPI.uasset
  VRGuild/Content/Hall/Board/Notice/A_NoticeBoard.uasset
  VRGuild/Content/Hall/Board/Notice/A_ReviewNotice.uasset
  VRGuild/Content/Resgister/UI/Review/WBP_DeveloperReview.uasset
  VRGuild/Content/main/2_Hall/L_Hall2.umap
  VRGuild/Source/VRGuild/Private/Global/Actors/CABasePoster.cpp
  VRGuild/Source/VRGuild/Private/Hall/Board/CANoticeBoard.cpp
  VRGuild/Source/VRGuild/Private/Hall/Board/CAReviewNotice.cpp
  VRGuild/Source/VRGuild/Private/Hall/Board/Notice/CAProjectNotice.cpp
  VRGuild/Source/VRGuild/Public/Global/API/BPL/CBPLDeveloper.h
  VRGuild/Source/VRGuild/Public/Global/Actors/CABasePoster.h
  VRGuild/Source/VRGuild/Public/Hall/Board/CANoticeBoard.h
  VRGuild/Source/VRGuild/Public/Hall/Board/CAReviewNotice.h
  VRGuild/Source/VRGuild/Public/Hall/Board/Notice/CAProjectNotice.h
Labels: ⚡️ 기능

#419 Alpha final build.
  VRGuild/Config/DefaultEngine.ini
  VRGuild/Content/Character/UI/PortalUI_Temp/WBP_Portal_Entry1.uasset
  VRGuild/Content/Character/UI/PortalUI_Temp/WBP_Portal_RoomList1.uasset
  VRGuild/Content/Global/UI/NewWidgetBlueprint.uasset
  VRGuild/Content/Hall/Blueprints/BP_CharacterHallPlayer.uasset
  VRGuild/Content/Hall/Board/Notice/A_NoticeBoard.uasset
  VRGuild/Content/Resgister/UI/Review/WBP_DeveloperReview.uasset
  VRGuild/Content/main/2_Hall/L_Hall2.umap
  VRGuild/Source/VRGuild/Private/Global/Widgets/TestWidgetComp.cpp
  VRGuild/Source/VRGuild/Private/Hall/Board/CANoticeBoard.cpp
  VRGuild/Source/VRGuild/Public/Global/Widgets/TestWidgetComp.h
  VRGuild/Source/VRGuild/Public/Hall/Board/CANoticeBoard.h
  VRGuild/Source/VRGuild/TP_ThirdPerson/TP_ThirdPersonCharacter.cpp
  VRGuild/Source/VRGuild/TP_ThirdPerson/TP_ThirdPersonCharacter.h
Labels: 🎉 배포

#421 Feat : NPC Player
  VRGuild/Content/Character/Player/Animation/montage/AM_SittoStand.uasset
  VRGuild/Content/Hall/Blueprints/BP_BarManager.uasset
  VRGuild/Content/NPC/Animation/AM_npc_VictoryIdle.uasset
  VRGuild/Content/NPC/Animation/AN_npc_LookingAround_UE.uasset
  VRGuild/Content/NPC/Animation/AN_npc_SearchingPockets_UE.uasset
  VRGuild/Content/NPC/Animation/AN_npc_SittingClap_UE.uasset
  VRGuild/Content/NPC/Animation/AN_npc_SittingGunMotion_UE.uasset
  VRGuild/Content/NPC/Animation/AN_npc_SittingTalking_UE.uasset
  VRGuild/Content/NPC/Animation/AN_npc_SittingTalking_UE1.uasset
  VRGuild/Content/NPC/Animation/AN_npc_SittingThumbsUp_UE.uasset
  VRGuild/Content/NPC/Animation/AN_npc_StandTalking_UE.uasset
  VRGuild/Content/NPC/Animation/AN_npc_Talking_UE.uasset
  VRGuild/Content/NPC/Animation/AN_npc_VictoryIdle_UE.uasset
  VRGuild/Content/NPC/Animation/AN_npc_seller_VictoryIdle_UE.uasset
  VRGuild/Content/NPC/Animation/AnimInstance/AN_npc_ABP_Manny.uasset
  VRGuild/Content/NPC/Animation/AnimInstance/AN_npc_ABP_Manny2.uasset
  VRGuild/Content/NPC/Animation/AnimInstance/AN_npc_ABP_Manny3.uasset
  VRGuild/Content/NPC/Animation/AnimInstance/AN_npc_ABP_Manny4.uasset
  VRGuild/Content/NPC/Animation/AnimInstance/AN_npc_ABP_Manny5.uasset
  VRGuild/Content/NPC/Animation/Mixamo/LookingAround_UE.uasset
  VRGuild/Content/NPC/Animation/Mixamo/SearchingPockets_UE.uasset
  VRGuild/Content/NPC/Animation/Mixamo/SittingClap_UE.uasset
  VRGuild/Content/NPC/Animation/Mixamo/SittingGunMotion_UE.uasset
  VRGuild/Content/NPC/Animation/Mixamo/SittingTalking_UE.uasset
  VRGuild/Content/NPC/Animation/Mixamo/SittingThumbsUp_UE.uasset
  VRGuild/Content/NPC/Animation/Mixamo/StandTalking_UE.uasset
  VRGuild/Content/NPC/Animation/Mixamo/Talking_UE.uasset
  VRGuild/Content/NPC/Animation/Mixamo/VictoryIdle_UE.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer1.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer2.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer3.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer4.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer5.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer6.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer7.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer8.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer9.uasset
  VRGuild/Content/NPC/Blueprints/BP_ThirdPersonCharacter.uasset
  VRGuild/Content/NPC/Blueprints/BP_ThirdPersonCharacter1.uasset
  VRGuild/Source/VRGuild/Private/CACChair.cpp
  VRGuild/Source/VRGuild/Private/TP_ThirdPerson/TP_ThirdPersonNpc.cpp
  VRGuild/Source/VRGuild/Public/CACChair.h
  VRGuild/Source/VRGuild/Public/TP_ThirdPerson/TP_ThirdPersonNpc.h
Labels: ⚡️ 기능

#423 포탈문 추가
  VRGuild/Content/Effect/Portal/Portal_Effect_MT.uasset
  VRGuild/Content/Hall/materials/props_materials/PortalFrame.uasset
  VRGuild/Content/Hall/meshes/props/PortalFrame_v001.uasset
  VRGuild/Content/Hall/textures/props_textures/Portal/PortalFrame_v001_PortalFrame_BaseColor.uasset
  VRGuild/Content/Hall/textures/props_textures/Portal/PortalFrame_v001_PortalFrame_Normal.uasset
  VRGuild/Content/Hall/textures/props_textures/Portal/PortalFrame_v001_PortalFrame_OcclusionRoughnessMetallic.uasset
Labels: 🎨 스타일

#427 Feat : Player Sit Animation
  VRGuild/Content/Character/Components/AC_SitChair.uasset
  VRGuild/Content/Character/Player/Animation/AM_player_sit2.uasset
  VRGuild/Content/Character/Player/Animation/AM_player_stand2.uasset
  VRGuild/Content/Character/Player/Animation/AN_player_sit2.uasset
  VRGuild/Content/Character/Player/Animation/AN_player_stand2.uasset
  VRGuild/Content/Character/Player/Animation/montage/AC_AnimMontage.uasset
  VRGuild/Content/Hall/Blueprints/BP_CharacterHallPlayer.uasset
  VRGuild/Content/TileSystem/Mesh/test/Sitting_chair.uasset
  VRGuild/Source/VRGuild/Public/Global/Components/CACCharacterAnimMontage.h
Labels: ⚡️ 기능

#446 Feat : Banner UI design and Animation
  VRGuild/Content/Character/UI/MainMenu/Team/WBP_CharacterTeam.uasset
  VRGuild/Content/Global/UI/Assets/Banner/TX_Banner_BG_B2.uasset
  VRGuild/Content/Global/UI/Assets/Banner/TX_Banner_BG_T2.uasset
  VRGuild/Content/Global/UI/Assets/Banner/TX_corner_banner_LB.uasset
  VRGuild/Content/Global/UI/Assets/Banner/TX_corner_banner_LT.uasset
  VRGuild/Content/Global/UI/Assets/Banner/TX_corner_banner_RB.uasset
  VRGuild/Content/Global/UI/Assets/Banner/TX_corner_banner_RT.uasset
  VRGuild/Content/Global/UI/Banner/WBP_Dynamic_banner_BackGround.uasset
  VRGuild/Content/Global/UI/Banner/WBP_Dynamic_banner_left.uasset
  VRGuild/Content/Global/UI/Banner/WBP_Dynamic_banner_right.uasset
  VRGuild/Content/Global/UI/Banner/WBP_banner_TeamMemberList.uasset
  VRGuild/Content/Global/UI/Banner/WBP_banner_Team_Menu.uasset
  VRGuild/Content/Hall/Board/Notice/UI/Team/WBP_Notice_Team.uasset
  VRGuild/Content/Hall/Board/Notice/UI/Team/WBP_TeamLeader.uasset
  VRGuild/Content/Hall/Board/Notice/UI/Team/WBP_TeamMemberList.uasset
  VRGuild/Content/Hall/Board/Notice/UI/Team/WBP_Team_MainMenu.uasset
  VRGuild/Content/Hall/Board/Notice/UI/WBP_Notice_Detail_Paper.uasset
  VRGuild/Content/Hall/Board/Notice/UI/WBP_Notice_comment_view.uasset
  VRGuild/Content/Hall/Board/Notice/UI/WBP_PlayerStatus.uasset
Labels: ⚡️ 기능

#448 깃발 추가
  VRGuild/Content/Hall/materials/props_materials/Flag_Mt.uasset
  VRGuild/Content/Hall/materials/props_materials/Flag_Mt1.uasset
  VRGuild/Content/Hall/meshes/props/Flag_v002_Flag_Long.uasset
  VRGuild/Content/Hall/meshes/props/Flag_v002_Flag_Main.uasset
  VRGuild/Content/Hall/meshes/props/Flag_v002_Flag_Under.uasset
  VRGuild/Content/Hall/textures/props_textures/Flag/Alpha.uasset
  VRGuild/Content/Hall/textures/props_textures/Flag/Flag_v001_lambert1_BaseColor.uasset
Labels: 🎨 스타일

#452 fix_NPC player to place Level
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer11.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer12.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer2.uasset
  VRGuild/Content/main/2_Hall/L_Hall2.umap
Labels: 🎨 스타일

#458 457 banner cloth simulation
  VRGuild/Content/Hall/Blueprints/A_Displayer.uasset
  VRGuild/Content/Hall/Blueprints/BP_CharacterHallPlayer.uasset
  VRGuild/Content/Hall/Board/Notice/UI/WBP_ProjectNoticeFrontSide_NoBackground.uasset
  VRGuild/Content/Hall/materials/props_materials/Board_Mt.uasset
  VRGuild/Content/Hall/materials/props_materials/Flag_Mt.uasset
  VRGuild/Content/Hall/materials/props_materials/Flag_Mt1.uasset
  VRGuild/Content/Hall/meshes/props/Flag_v002_Flag_Long.uasset
  VRGuild/Content/Hall/meshes/props/Flag_v002_Flag_Main.uasset
  VRGuild/Content/Hall/meshes/props/SKM/NIVR.uasset
  VRGuild/Content/Hall/meshes/props/SKM/NIVRTest.uasset
  VRGuild/Content/Hall/meshes/props/SKM/NIVRTest_PhysicsAsset.uasset
  VRGuild/Content/Hall/meshes/props/SKM/NIVRTest_Skeleton.uasset
  VRGuild/Content/Hall/meshes/props/SKM/NIVR_PhysicsAsset.uasset
  VRGuild/Content/Hall/meshes/props/SKM/NIVR_Skeleton.uasset
  VRGuild/Content/Hall/meshes/props/SKM/SKM_Board_v001_Board.uasset
  VRGuild/Content/Hall/meshes/props/SKM/SKM_Flag_v002_Flag_Main.uasset
  VRGuild/Content/Hall/meshes/props/SKM/SK_Board_v001_Board.uasset
  VRGuild/Content/Hall/meshes/props/SKM/SK_Flag_v002_Flag_Main.uasset
  VRGuild/Content/Hall/meshes/props/SKM/SK_Flag_v002_Flag_Main_P.uasset
  VRGuild/Content/Hall/meshes/props/SKM/anotherplane.uasset
  VRGuild/Content/Hall/meshes/props/SKM/anotherplane_PhysicsAsset.uasset
  VRGuild/Content/Hall/meshes/props/SKM/anotherplane_Skeleton.uasset
  VRGuild/Source/VRGuild/Public/Hall/Actors/CADisplayer.h
  VRGuild/VRGuild.uproject
Labels: ⚡️ 기능

#461 fix player Team selection UI
  VRGuild/Content/Character/UI/MainMenu/Team/WBP_EmailButton.uasset
  VRGuild/Content/Character/UI/MainMenu/Team/WBP_PortfolioButton.uasset
  VRGuild/Content/Character/UI/WidgetComponent/WBP_team_select_list.uasset
  VRGuild/Content/Global/PDF/BluePrint/WBP_PDF.uasset
  VRGuild/Content/main/2_Hall/L_Hall2.umap
Labels: ♻️ 리펙토링

#469 Update data when banner is placed
  VRGuild/Content/Character/UI/MainMenu/Team/WBP_CharacterTeam.uasset
  VRGuild/Content/Global/UI/Banner/WBP_Dynamic_banner_left.uasset
  VRGuild/Content/Global/UI/Banner/WBP_Dynamic_banner_right.uasset
  VRGuild/Content/Global/UI/Banner/WBP_banner_Team_Menu.uasset
  VRGuild/Content/Hall/Blueprints/A_Displayer.uasset
  VRGuild/Content/Hall/Board/Notice/UI/Team/WBP_Team_MainMenu.uasset
  VRGuild/Content/Hall/meshes/props/SKM/SKM_Flag_v002_Flag_Main.uasset
  VRGuild/Content/Hall/meshes/props/SKM/anotherplane.uasset
Labels: ♻️ 리펙토링, 💻 작업

#471 Banner flag collision added
  VRGuild/Content/Hall/Blueprints/A_Displayer.uasset
  VRGuild/Content/Hall/meshes/props/SKM/FlagCombined.uasset
  VRGuild/Content/Hall/meshes/props/SKM/FlagCombined_PhysicsAsset.uasset
  VRGuild/Content/Hall/meshes/props/SKM/FlagCombined_Skeleton.uasset
  VRGuild/Content/main/2_Hall/L_Hall2.umap
Labels: ⚡️ 기능, 💻 작업

#473 Add npc nick name and Stat Logo
  VRGuild/Content/NPC/Blueprints/BP_NpcBase_Nomal.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer1.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer11.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer12.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer2.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer3.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer4.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer5.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer6.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer7.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer8.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer9.uasset
Labels: 🎨 스타일

#485 457 banner cloth simulation 1
  VRGuild/Config/DefaultEngine.ini
  VRGuild/Content/Global/UI/Banner/WBP_Dynamic_banner_right.uasset
  VRGuild/Content/Global/UI/Banner/WBP_banner_TeamMemberList.uasset
  VRGuild/Content/Global/UI/Banner/WBP_banner_Team_Menu.uasset
  VRGuild/Content/Hall/Blueprints/A_Displayer.uasset
  VRGuild/Content/Hall/Board/Notice/A_ProjectNotice.uasset
  VRGuild/Content/Hall/Board/Notice/UI/Team/WBP_Notice_Team.uasset
  VRGuild/Content/Hall/Board/Notice/UI/Team/WBP_TeamLeader.uasset
  VRGuild/Content/Hall/Board/Notice/UI/WBP_ProjectNoticeFrontSide.uasset
  VRGuild/Content/Hall/Board/Notice/UI/WBP_ProjectNoticeFrontSide_NoBackground.uasset
  VRGuild/Content/Hall/meshes/props/SKM/FlagCombined.uasset
  VRGuild/Content/TPS/ThirdPerson/Blueprints/BP_ThirdPersonCharacter.uasset
  VRGuild/Content/TPS/ThirdPerson/Input/IMC_Default.uasset
  VRGuild/Source/VRGuild/Private/Global/Components/CACInteraction.cpp
  VRGuild/Source/VRGuild/Private/Global/UI/API/CWGBaseAPI.cpp
  VRGuild/Source/VRGuild/TP_ThirdPerson/TP_ThirdPersonCharacter.cpp
Labels: ♻️ 리펙토링

#497 Notice stuff
  VRGuild/Content/Hall/Blueprints/A_Displayer.uasset
  VRGuild/Content/Hall/Blueprints/BP_CharacterHallPlayer.uasset
  VRGuild/Content/Hall/Board/Notice/A_NoticeBoard.uasset
  VRGuild/Content/Hall/Board/Notice/A_ReviewNotice.uasset
  VRGuild/Content/Resgister/UI/Review/WBP_DeveloperReview.uasset
  VRGuild/Source/VRGuild/Private/Global/Actors/CABasePoster.cpp
  VRGuild/Source/VRGuild/Private/Global/CACarryInteractable.cpp
  VRGuild/Source/VRGuild/Private/Global/Components/CACCarry.cpp
  VRGuild/Source/VRGuild/Private/Hall/Board/CANoticeBoard.cpp
  VRGuild/Source/VRGuild/Public/Global/Components/CACCarry.h
  VRGuild/Source/VRGuild/Public/Hall/Board/CANoticeBoard.h
Labels: 💻 작업

#521 Dv npc voice remix
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer11.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer12.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer13.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer15.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer6.uasset
  VRGuild/Content/NPC/Blueprints/BP_NpcPlayer7.uasset
  VRGuild/Content/NPC/Voice/campfire_Cue.uasset
  VRGuild/Content/NPC/Voice/voice1-speech.uasset
  VRGuild/Content/NPC/Voice/voice1-speech_Cue.uasset
  VRGuild/Content/NPC/Voice/voice2-a_Cue.uasset
  VRGuild/Content/NPC/Voice/voice2-b.uasset
  VRGuild/Content/NPC/Voice/voice2-b_Cue.uasset
  VRGuild/Content/NPC/Voice/voice2-c_Cue.uasset
  VRGuild/Content/NPC/Voice/voice3-a.uasset
  VRGuild/Content/NPC/Voice/voice3-a_Cue.uasset
  VRGuild/Content/NPC/Voice/voice3-b_Cue.uasset
  VRGuild/Content/main/2_Hall/L_Hall2.umap
Labels: ♻️ 리펙토링
