Repository VRGuild/VRGuild, pull requests merged in 2024-10, with the labels that each got.

#35 > ⚡️ Feat : Client and server build successful.
  VRGuild/Config/DefaultEngine.ini
  VRGuild/Config/DefaultInput.ini
  VRGuild/Source/VRGuild/Private/Global/CGIGameInstance.cpp
  VRGuild/Source/VRGuild/Private/Global/Server/CGMBaseServer.cpp
  VRGuild/Source/VRGuild/Private/Global/Server/CGSSBaseGameSession.cpp
  VRGuild/Source/VRGuild/Private/Global/Server/CPCBasePlayerController.cpp
  VRGuild/Source/VRGuild/Public/Global/CGIGameInstance.h
  VRGuild/Source/VRGuild/Public/Global/Server/CGMBaseServer.h
  VRGuild/Source/VRGuild/Public/Global/Server/CGSSBaseGameSession.h
  VRGuild/Source/VRGuild/Public/Global/Server/CPCBasePlayerController.h
  VRGuild/Source/VRGuild/VRGuild.Build.cs
  VRGuild/Source/VRGuildClient.Target.cs
  VRGuild/Source/VRGuildServer.Target.cs
  VRGuild/VRGuild.uproject
Labels: ⚡️ 기능

#50 🛠️ Fix : Create & Delete function make to virtual
  VRGuild/Source/VRGuild/Public/TileSystem/CATileZone.h
Labels: 🛠️ 수정

#68 ⚡️ Feat : Add Token API
  VRGuild/Content/Global/API/AC_LoginAPI.uasset
  VRGuild/Content/Global/API/A_BaseAPI.uasset
  VRGuild/Content/Global/Server/PC_BasePlayerController.uasset
  VRGuild/Source/VRGuild/Private/Global/API/CABaseAPI.cpp
  VRGuild/Source/VRGuild/Private/Global/API/CACBaseAPI.cpp
  VRGuild/Source/VRGuild/Private/Global/API/CACLoginAPI.cpp
  VRGuild/Source/VRGuild/Private/Global/Server/CPCBasePlayerController.cpp
  VRGuild/Source/VRGuild/Public/Global/API/CABaseAPI.h
  VRGuild/Source/VRGuild/Public/Global/API/CACBaseAPI.h
  VRGuild/Source/VRGuild/Public/Global/API/CACLoginAPI.h
  VRGuild/Source/VRGuild/Public/Global/Server/CPCBasePlayerController.h
Labels: ⚡️ 기능, 🛠️ 수정

#190 88 pl interaction system 4
  VRGuild/Content/Hall/Blueprints/A_Displayer.uasset
  VRGuild/Source/VRGuild/Private/Global/CACarryInteractable.cpp
  VRGuild/Source/VRGuild/Private/Global/CAInteractable.cpp
  VRGuild/Source/VRGuild/Private/Global/Components/CACCarry.cpp
  VRGuild/Source/VRGuild/Private/Global/Components/CACInteraction.cpp
  VRGuild/Source/VRGuild/Private/Hall/Actors/CADisplayer.cpp
  VRGuild/Source/VRGuild/Public/Global/CACarryInteractable.h
  VRGuild/Source/VRGuild/Public/Global/CAInteractable.h
  VRGuild/Source/VRGuild/Public/Global/Components/CACCarry.h
  VRGuild/Source/VRGuild/Public/Global/Components/CACInteraction.h
  VRGuild/Source/VRGuild/Public/Global/Interfaces/CIInteractionInterface.h
  VRGuild/Source/VRGuild/Public/Hall/Actors/CADisplayer.h
  VRGuild/Source/VRGuild/TP_ThirdPerson/TP_ThirdPersonCharacter.cpp
  VRGuild/Source/VRGuild/TP_ThirdPerson/TP_ThirdPersonCharacter.h
Labels: ♻️ 리펙토링

#193 Feat - Update Poster Widget before sending it to CADisplayer Actor in…
  VRGuild/Content/Hall/Board/Notice/A_ProjectNotice.uasset
  VRGuild/Content/Hall/Board/Notice/UI/WBP_NoticeFull.uasset
  VRGuild/Source/VRGuild/Private/Global/CACarryInteractable.cpp
  VRGuild/Source/VRGuild/Private/Global/Components/CACCarry.cpp
  VRGuild/Source/VRGuild/Private/Hall/Actors/CADisplayer.cpp
  VRGuild/Source/VRGuild/Private/Hall/Board/Notice/CAProjectNotice.cpp
  VRGuild/Source/VRGuild/Private/Hall/Board/Notice/UI/CWGProjectNoticeFull.cpp
  VRGuild/Source/VRGuild/Public/Global/CACarryInteractable.h
  VRGuild/Source/VRGuild/Public/Global/UI/API/CWGProjectAPI.h
  VRGuild/Source/VRGuild/Public/Hall/Board/Notice/CAProjectNotice.h
  VRGuild/Source/VRGuild/Public/Hall/Board/Notice/UI/CWGProjectNoticeFull.h
Labels: ⚡️ 기능

#209 137 dv interaction system npc 1
  VRGuild/Content/Character/Custom/Blueprints/BP_CharacterCustomPlayer.uasset
  VRGuild/Content/Character/Player/Animation/AN_ABP_Manny_Child.uasset
  VRGuild/Content/Character/UI/Popup/WBP_character_popup_custom2.uasset
  VRGuild/Content/Character/UI/Popup/WBP_character_popup_gamequit.uasset
  VRGuild/Content/Character/UI/Popup/WBP_character_popup_quest1.uasset
  VRGuild/Content/Character/UI/Popup/WBP_character_popup_quest2.uasset
  VRGuild/Content/Character/UI/Popup/WBP_character_popup_throwaway.uasset
  VRGuild/Content/Character/UI/WBP_CharacterSkill.uasset
  VRGuild/Content/Character/UI/WBP_Character_info.uasset
  VRGuild/Content/Character/UI/WidgetComponent/WBP_Button2.uasset
  VRGuild/Content/Character/UI/WidgetComponent/WBP_QuestList.uasset
  VRGuild/Content/Global/Input/Actions/IA_ESC.uasset
  VRGuild/Content/Global/UI/Widgets/WBP_Carryable.uasset
  VRGuild/Content/Hall/Blueprints/BP_BasePlayerController_Hall.uasset
  VRGuild/Content/Hall/Blueprints/BP_CharacterHallPlayer.uasset
  VRGuild/Content/Hall/Blueprints/MyCAReceptionist.uasset
  VRGuild/Content/NPC/UI/WBP_npc_popup_project3.uasset
  VRGuild/Content/Resgister/UI/Project/WBP_ProjectResgister_Leader.uasset
  VRGuild/Content/Resgister/UI/Review/WBP_ResgisterReview.uasset
  VRGuild/Content/Resgister/UI/register/WBP_Resgister.uasset
  VRGuild/Content/TPS/ThirdPerson/Blueprints/BP_ThirdPersonCharacter.uasset
  VRGuild/Content/TPS/ThirdPerson/Input/IMC_Default.uasset
  VRGuild/Source/VRGuild/Private/Character/Customize/CACCustomInteraction.cpp
  VRGuild/Source/VRGuild/Private/Global/Server/CPCBasePlayerController.cpp
  VRGuild/Source/VRGuild/Public/Global/Server/CPCBasePlayerController.h
  VRGuild/Source/VRGuild/TP_ThirdPerson/TP_ThirdPersonCharacter.cpp
  VRGuild/Source/VRGuild/TP_ThirdPerson/TP_ThirdPersonCharacter.h
Labels: ♻️ 리펙토링

#213 Add Prop + Lighting,PostProduction
  VRGuild/Content/Hall/LevelInstance/BPP_Bar_Pack.uasset
  VRGuild/Content/Hall/LevelInstance/Bar_Pack.umap
  VRGuild/Content/Hall/materials/Window.uasset
  VRGuild/Content/Hall/materials/building_materials/Bar_Main_Table_MT.uasset
  VRGuild/Content/Hall/materials/building_materials/Bar_prop_1_Mt.uasset
  VRGuild/Content/Hall/materials/building_materials/Info_Mt.uasset
  VRGuild/Content/Hall/materials/building_materials/base_materials/MI_wooden_board_01_Inst.uasset
  VRGuild/Content/Hall/materials/building_materials/base_materials/M_brick.uasset
  VRGuild/Content/Hall/materials/props_materials/Board_Mt.uasset
  VRGuild/Content/Hall/meshes/building/Bar_Bar_Prop_1_8.uasset
  VRGuild/Content/Hall/meshes/building/Bar_Ork_1.uasset
  VRGuild/Content/Hall/meshes/building/Bar_Ork_2.uasset
  VRGuild/Content/Hall/meshes/props/Board_v001_Board.uasset
  VRGuild/Content/Hall/meshes/props/Board_v001_Board_long.uasset
  VRGuild/Content/Hall/textures/props_textures/Board/Board_v001_Board_Mt_BaseColor.uasset
  VRGuild/Content/Hall/textures/props_textures/Board/Board_v001_Board_Mt_Normal.uasset
  VRGuild/Content/Hall/textures/props_textures/Board/Board_v001_Board_Mt_OcclusionRoughnessMetallic.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/0/PQ/BJEDB96MS3I2DES46XI59B.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/1/6I/INV3QOYUU7NR943S1TBAQ6.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/2/B0/D3W9YJ8E8OH2T9Z67NM3M3.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/3/25/NR6AF8CLNUYAOG9PZUJC0P.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/3/2X/0Q9JH2G0AX2U0ADXC81U2R.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/4/LL/QAZVJ55A2D3VSW6HOUGM8W.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/4/Y6/YWMVRL2LRD0NSB721CX1SF.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/5/MR/GK2VPFIU9T3EDC1KLN9I1J.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/6/DV/K7SCG95ZDAPUC1MW0DGH1Q.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/6/MS/WHA373X6O4KB90K2LK2UTI.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/6/TJ/J63Q6EBP3C4RP8X6QA9ZLZ.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/7/8N/202ACAO4A7KA2CO25LGDKD.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/7/DL/D1W1QYNLSZT403RM4JJ9FD.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/7/J0/SO2LXCR658731VPXITGS8R.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/8/C9/RBDJKBM31MR2GZ9KIOU91Z.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/9/AT/LY32UKDP4GQZFDGXJFR3A3.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/9/CX/X9SJSHSUO6A0D15TVDCE2N.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/9/IH/LYIA4NDHTX8PLPW5EL0TIX.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/9/J4/7KFSI4SPXRURWZFJ8TN6KY.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/9/YU/W6QSR1QDZ7P3S7H7C7NE5I.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/A/0U/Y5I2M9IMM3YZTSY7HN2S2S.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/A/82/YO1UZY32TY771A81OFTNXU.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/A/JL/PJO2FMMOJ4PFUHI3B6V91U.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/B/VQ/XGYRILQ0ZNGOLD7T73PTXB.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/C/JO/10FOQSWQSRN39LO5KHYGCT.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/C/PP/TW7FNA4RGIWJ1TI7Z49SH5.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/C/WD/K3W3F29GO9FM6TQGGF1EGP.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/C/XO/GWI2BPYWZVC6ZNIM1RY3OU.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/D/RC/JOWJO07LN95QFZKG2UG4P5.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/D/RP/IS8UQCF4R20XVDPSLRRN0S.uasset
  VRGuild/Content/__ExternalActors__/Hall/LevelInstance/Bar_Pack/E/RU/Q604UK8IE9YF6E03W3QKPI.uasset
Labels: 🎨 스타일

#214 NPC 상인 추가
  VRGuild/Content/Character/NPC/Material/NPC_Seller_Mt.uasset
  VRGuild/Content/Character/NPC/Mesh/NPC_Seller.uasset
  VRGuild/Content/Character/NPC/Mesh/NPC_Seller_PhysicsAsset.uasset
  VRGuild/Content/Character/NPC/Mesh/NPC_Seller_Skeleton.uasset
  VRGuild/Content/Character/NPC/Texture/Seller/NPC_v001_NPC_Seller_Mt_BaseColor.uasset
  VRGuild/Content/Character/NPC/Texture/Seller/NPC_v001_NPC_Seller_Mt_Normal.uasset
  VRGuild/Content/Character/NPC/Texture/Seller/NPC_v001_NPC_Seller_Mt_OcclusionRoughnessMetallic.uasset
Labels: 🎨 스타일

#224 Portal Actor
  VRGuild/Config/DefaultEngine.ini
  VRGuild/Content/Character/UI/PortalUI_Temp/WBP_Portal_Entry1.uasset
  VRGuild/Content/Character/UI/PortalUI_Temp/WBP_Portal_RoomList1.uasset
  VRGuild/Content/Character/UI/PortalUI_Temp/WBP_popup_portal_create1.uasset
  VRGuild/Content/Global/A_Portal.uasset
  VRGuild/Content/TPS/ThirdPerson/Blueprints/BP_ThirdPersonCharacter.uasset
  VRGuild/Content/TileSystem/Blueprints/A_TileFloor.uasset
  VRGuild/Content/TileSystem/Blueprints/GM_CharacterCubeLand.uasset
  VRGuild/Content/TileSystem/L_CubeLand.umap
  VRGuild/Content/main/2_Hall/L_Hall.umap
  VRGuild/Content/main/L_CubeLand.umap
  VRGuild/Source/VRGuild/Private/Hall/Actors/CAPortal.cpp
  VRGuild/Source/VRGuild/Public/Hall/Actors/CAPortal.h
  VRGuild/Source/VRGuild/TP_ThirdPerson/TP_ThirdPersonCharacter.cpp
Labels: ⚡️ 기능

#229 Switch back to BP_CharacterHallPlayer
  VRGuild/Content/Hall/Blueprints/GM_Hall.uasset
Labels: 🐝 버그

#242 Positional voice chat
  VRGuild/Content/Global/Voice/ATT_Voice.uasset
  VRGuild/Content/Hall/Blueprints/BP_BasePlayerController_Hall.uasset
  VRGuild/Content/Hall/Blueprints/BP_CharacterHallPlayer.uasset
  VRGuild/Source/VRGuild/Private/Global/Server/CPCBasePlayerController.cpp
  VRGuild/Source/VRGuild/Public/Global/Server/CPCBasePlayerController.h
  VRGuild/VRGuild.uproject
Labels: 💻 작업

#243 232 dv user team create
  VRGuild/Content/Global/UI/Widgets/WBP_Carryable.uasset
  VRGuild/Content/Hall/Board/Notice/UI/WBP_NoticeFull.uasset
  VRGuild/Content/Hall/Board/Notice/UI/WBP_Notice_Detail_Paper.uasset
  VRGuild/Content/Hall/Board/Notice/UI/WBP_Notice_Team.uasset
  VRGuild/Source/VRGuild/Private/Global/API/BPL/CBPLTeam.cpp
  VRGuild/Source/VRGuild/Private/Global/API/CACBaseAPI.cpp
  VRGuild/Source/VRGuild/Private/Global/CGIGameInstance.cpp
  VRGuild/Source/VRGuild/Private/Global/Server/CPCBasePlayerController.cpp
  VRGuild/Source/VRGuild/Private/Global/UI/API/CWGBaseAPI.cpp
  VRGuild/Source/VRGuild/Private/Global/UI/API/CWGTeamAPI.cpp
  VRGuild/Source/VRGuild/Public/Global/API/BPL/CBPLTeam.h
  VRGuild/Source/VRGuild/Public/Global/CGIGameInstance.h
  VRGuild/Source/VRGuild/Public/Global/Server/CPCBasePlayerController.h
  VRGuild/Source/VRGuild/Public/Global/UI/API/CWGTeamAPI.h
Labels: ⚡️ 기능

#251 Fix Interaction UI + ESC menu bug.
  VRGuild/Content/Character/UI/WBP_Character_info.uasset
  VRGuild/Content/Hall/Blueprints/BP_CharacterHallPlayer.uasset
  VRGuild/Source/VRGuild/Private/Global/Components/CACCarry.cpp
  VRGuild/Source/VRGuild/Public/Global/Components/CACCarry.h
  VRGuild/Source/VRGuild/TP_ThirdPerson/TP_ThirdPersonCharacter.cpp
Labels: 🐝 버그

#260 185 dv interaction system displayer 1
  VRGuild/Content/Character/Player/Animation/AN_ABP_Manny.uasset
  VRGuild/Content/Global/Voice/ATT_Voice.uasset
  VRGuild/Content/Hall/Blueprints/BP_BasePlayerController_Hall.uasset
  VRGuild/Content/Hall/Board/Notice/UI/WBP_Notice_Team.uasset
  VRGuild/Content/TPS/ThirdPerson/Blueprints/BP_ThirdPersonCharacter.uasset
Labels: 💻 작업
